# =============================================================================
# ServiceAccount — IRSA (IAM Roles for Service Accounts)
# =============================================================================
# This ServiceAccount is annotated with an IAM role ARN.
# When a pod uses this ServiceAccount, it automatically gets temporary
# AWS credentials for that IAM role — no need for access keys!
#
# The IAM role ARN should be set after terraform apply creates the role.
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-ops-sa
  namespace: kubeflow-ops
  annotations:
    # Replace with actual IAM role ARN after terraform apply
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/kubeflow-ops-dev-app-role"
  labels:
    app.kubernetes.io/part-of: kubeflow-ops
