# =============================================================================
# ArgoCD Application — Common Resources (Namespace, SA, ConfigMap, Ingress)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-resources
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kubeflow-ops
    type: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/kubeflow-ops.git
    targetRevision: main
    path: gitops/apps/common
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow-ops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
