# =============================================================================
# ArgoCD Application — External Secrets Operator
# =============================================================================
# External Secrets Operator syncs secrets from AWS Secrets Manager into
# Kubernetes Secrets automatically. This means:
# - No hardcoded passwords in YAML files
# - No base64-encoded secrets committed to Git
# - Secrets are rotated in AWS and automatically updated in the cluster
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kubeflow-ops
    type: security
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io/
    chart: external-secrets
    targetRevision: 0.10.7
    helm:
      releaseName: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
