# =============================================================================
# ArgoCD Application — Kyverno (Policy Engine)
# =============================================================================
# Kyverno enforces security policies on your cluster. If someone tries to
# deploy a pod that violates a policy, Kyverno blocks it.
#
# Example: A developer tries to deploy without resource limits →
#          Kyverno rejects the deployment with a clear error message.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kubeflow-ops
    type: security
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.2.7
    helm:
      releaseName: kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
