# ArgoCD Application — Notification Service
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kubeflow-ops
    type: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/kubeflow-ops.git
    targetRevision: main
    path: gitops/apps/notification-service/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow-ops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
